#!/bin/bash

mkdir bin 2> /dev/null #if folder already exists, send error message
                       #ignore the error message
# WARNING: If you don't have permission to create this folder,
# there won't be any message about this.


javac  -sourcepath src/  -d bin src/dwdm/intersection/*.java || exit


java -cp bin/ dwdm.intersection.BasicJoin resources/test1.txt resources/test2.txt
